spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: root
    password: root
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: create # When you launch the application for the first time - switch "none" at "create"
#    show-sql: true
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    open-in-view: false
#    generate-ddl: true
logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG
server:
  error:
    include-stacktrace: on_param
